### PR TITLE
Update to django 3.0

### PR DESCRIPTION
**Pull request by julfy**

### CODE REVIEW

**Comment by RevolutionTech** [comment]
# [Codecov](https://codecov.io/gh/infoscout/emailengine/pull/20?src=pr&el=h1) Report
> Merging [#20](https://codecov.io/gh/infoscout/emailengine/pull/20?src=pr&el=desc) into [master](https://codecov.io/gh/infoscout/emailengine/commit/0d2da6762874b460ba5aff793fbe6ab6818085ca&el=desc) will **not change** coverage by `%`.
> The diff coverage is `n/a`.

[Impacted file tree graph](https://codecov.io/gh/infoscout/emailengine/pull/20?src=pr&el=tree)

```diff
@@            Coverage Diff            @@
##            master       #20   +/-   ##
=========================================
  Coverage   100.00%   100.00%           
=========================================
  Files           12        13    +1     
  Lines          372       374    +2     
=========================================
+ Hits           372       374    +2     
```


| [Impacted Files](https://codecov.io/gh/infoscout/emailengine/pull/20?src=pr&el=tree) | Coverage Δ | |
|---|---|---|
| [emailengine/migrations/\_\_init\_\_.py](https://codecov.io/gh/infoscout/emailengine/pull/20/diff?src=pr&el=tree#diff-ZW1haWxlbmdpbmUvbWlncmF0aW9ucy9fX2luaXRfXy5weQ==) | `100.00% <0.00%> (ø)` | |

------

[Continue to review full report at Codecov](https://codecov.io/gh/infoscout/emailengine/pull/20?src=pr&el=continue).
> **Legend** - [Click here to learn more](https://docs.codecov.io/docs/codecov-delta)
> `Δ = absolute <relative> (impact)`, `ø = not affected`, `? = missing data`
> Powered by [Codecov](https://codecov.io/gh/infoscout/emailengine/pull/20?src=pr&el=footer). Last update [0d2da67...e7a96fe](https://codecov.io/gh/infoscout/emailengine/pull/20?src=pr&el=lastupdated). Read the [comment docs](https://docs.codecov.io/docs/pull-request-comments).

**Comment by RevolutionTech** [comment]
# [Codecov](https://codecov.io/gh/infoscout/emailengine/pull/20?src=pr&el=h1) Report
> Merging [#20](https://codecov.io/gh/infoscout/emailengine/pull/20?src=pr&el=desc) into [master](https://codecov.io/gh/infoscout/emailengine/commit/0d2da6762874b460ba5aff793fbe6ab6818085ca&el=desc) will **not change** coverage by `%`.
> The diff coverage is `n/a`.

[Impacted file tree graph](https://codecov.io/gh/infoscout/emailengine/pull/20?src=pr&el=tree)

```diff
@@            Coverage Diff            @@
##            master       #20   +/-   ##
=========================================
  Coverage   100.00%   100.00%           
=========================================
  Files           12        13    +1     
  Lines          372       374    +2     
=========================================
+ Hits           372       374    +2     
```


| [Impacted Files](https://codecov.io/gh/infoscout/emailengine/pull/20?src=pr&el=tree) | Coverage Δ | |
|---|---|---|
| [emailengine/migrations/\_\_init\_\_.py](https://codecov.io/gh/infoscout/emailengine/pull/20/diff?src=pr&el=tree#diff-ZW1haWxlbmdpbmUvbWlncmF0aW9ucy9fX2luaXRfXy5weQ==) | `100.00% <0.00%> (ø)` | |

------

[Continue to review full report at Codecov](https://codecov.io/gh/infoscout/emailengine/pull/20?src=pr&el=continue).
> **Legend** - [Click here to learn more](https://docs.codecov.io/docs/codecov-delta)
> `Δ = absolute <relative> (impact)`, `ø = not affected`, `? = missing data`
> Powered by [Codecov](https://codecov.io/gh/infoscout/emailengine/pull/20?src=pr&el=footer). Last update [0d2da67...e7a96fe](https://codecov.io/gh/infoscout/emailengine/pull/20?src=pr&el=lastupdated). Read the [comment docs](https://docs.codecov.io/docs/pull-request-comments).

**Comment by julfy** [comment]
sure

**Comment by RevolutionTech** [comment]
# [Codecov](https://codecov.io/gh/infoscout/emailengine/pull/20?src=pr&el=h1) Report
> Merging [#20](https://codecov.io/gh/infoscout/emailengine/pull/20?src=pr&el=desc) into [master](https://codecov.io/gh/infoscout/emailengine/commit/0d2da6762874b460ba5aff793fbe6ab6818085ca&el=desc) will **not change** coverage by `%`.
> The diff coverage is `n/a`.

[Impacted file tree graph](https://codecov.io/gh/infoscout/emailengine/pull/20?src=pr&el=tree)

```diff
@@            Coverage Diff            @@
##            master       #20   +/-   ##
=========================================
  Coverage   100.00%   100.00%           
=========================================
  Files           12        13    +1     
  Lines          372       374    +2     
=========================================
+ Hits           372       374    +2     
```


| [Impacted Files](https://codecov.io/gh/infoscout/emailengine/pull/20?src=pr&el=tree) | Coverage Δ | |
|---|---|---|
| [emailengine/migrations/\_\_init\_\_.py](https://codecov.io/gh/infoscout/emailengine/pull/20/diff?src=pr&el=tree#diff-ZW1haWxlbmdpbmUvbWlncmF0aW9ucy9fX2luaXRfXy5weQ==) | `100.00% <0.00%> (ø)` | |

------

[Continue to review full report at Codecov](https://codecov.io/gh/infoscout/emailengine/pull/20?src=pr&el=continue).
> **Legend** - [Click here to learn more](https://docs.codecov.io/docs/codecov-delta)
> `Δ = absolute <relative> (impact)`, `ø = not affected`, `? = missing data`
> Powered by [Codecov](https://codecov.io/gh/infoscout/emailengine/pull/20?src=pr&el=footer). Last update [0d2da67...53bb4c1](https://codecov.io/gh/infoscout/emailengine/pull/20?src=pr&el=lastupdated). Read the [comment docs](https://docs.codecov.io/docs/pull-request-comments).

**Pull request merged**
